### ISSUE TITLE
BlenderToMax (inverted work)

### ISSUE THREAD

**Issue by odil24** [jmdvella/3dsmax-scripts#1]
Hi.
Is it possible to write a script that can export as FBX from Blender to Max as inverted work (PrincipledBSDF to VRay material) via Python script?

**Comment by jmdvella** [comment]
Hi odil24, yes absolutely. You can modify the code and flip the variables around if you wish. I used maxscript in this case so you would have to change it to python if that suits your workflow.

**Comment by odil24** [comment]
Can you helps me on which line is for what in your .ms file?
Maybe will try to convert as much as i can of course.

**Comment by jmdvella** [comment]
Check the --comments in the maxscript. If you get stuck on a point let me know which line and ill explain to you what it does.
