### ISSUE TITLE
which version of 3ds max does the script supports?

### ISSUE THREAD

**Issue by mutouu** [jmdvella/3dsmax-scripts#2]
Thank you for sharing this script ,it may really help me to speed up my work,but I install it in my 3ds max 2021,the error blow was happened,how can i fix the issue?

![Capture](https://user-images.githubusercontent.com/95394051/170168098-d4a77160-dc14-48a8-b231-24444ee17f17.JPG)

**Comment by jmdvella** [comment]
Hi mutouu, was this related to the Normal DirectX > OpenGL (Optional) line 67 - 71?

**Comment by jmdvella** [comment]
Hi mutouu, please try the latest version of the script v01.01

This should resolve your issue
