### ISSUE TITLE
Error with line 58 when running the script

### ISSUE THREAD

**Issue by MatMachina** [jmdvella/3dsmax-scripts#3]
Hi,

I'm receiving this issue when running the script on Max 2022 and 2023.
I have zero coding knowledge, so I have no idea why.

![image](https://user-images.githubusercontent.com/110823697/183403350-dbf17ab2-2948-4808-84be-1183aa95dbea.png)

And of course, thank you so much for your amazing work!

**Comment by jmdvella** [comment]
Hi MatMachina,

Line 58 is regarding Opacity. Check if your opacity is a bitmap, if it's
just another type of node, remove it or replace it with a bitmap.

However I also notice that it mentions "normal_map". So this could be
related to the next line of code which is that the bitmap in the bump slot
needs to be a vray normal texture first. So if your normal texture is in
the bump slot put it first in the vray normal node eg:
[image: image.png]

Let me know if that works and which one it was (opacity or normal).

Cheers,
James Vella
www.jamesvella.net

**Comment by MatMachina** [comment]
Thanks so much mate!
The Normal Map was the culprit.

Unfortunately I'm getting this error now:

![image](https://user-images.githubusercontent.com/110823697/183412315-1821a62c-1e67-48e2-9606-ce0e8492fa8f.png)

**Comment by jmdvella** [comment]
This is because its looking for a DirectX or OpenGL in the normal bitmap
filename (Its optional), you can remove these lines of code if that doesnt
help your workflow. Ive attached a modified version of the script for you,
let me know if it works.



Cheers,
James Vella
www.jamesvella.net

**Comment by MatMachina** [comment]
That worked too! Thank you. You're awesome.

Gonna risk really getting on your nerves here but....... :/

![image](https://user-images.githubusercontent.com/110823697/183417868-bf318151-5f63-4db9-b705-dc9fc9da7f06.png)

**Comment by jmdvella** [comment]
Actually Im glad for the feedback, it lets me know I can add some pop up
messages to help users when an error occurs, so thanks!

Seems like the same error, ive just removed it entirely so hopefully that
fixes it (attached), if not send me a sample scene and ill see what the
problem is.


Cheers,
James Vella
www.jamesvella.net

**Comment by MatMachina** [comment]
Oh great. In that case I'm glad I can help somewhat.

I'm not seeing your attachment for some reason. Or am I just not looking properly?

**Comment by jmdvella** [comment]
Check its called modified2

**Comment by MatMachina** [comment]
I'm sorry mate, I'm really not seeing it.
It is supposed to be attached to your comment just like my screenshots are, right?

**Comment by jmdvella** [comment]
Yeah,

Ive uploaded it to google drive for you, heres the link
<https://drive.google.com/file/d/1wQiPL-9KUp00ksMLJqfYx9CX26KE-AsM/view?usp=sharing>
.

If that error occurs again open the script file from 3dsmax and remove
lines 63-67. You can do this by right clicking on the script > Edit Macro
Script > Remove the lines > File > save

[image: image.png]
[image: image.png]


Cheers,
James Vella
www.jamesvella.net

**Comment by MatMachina** [comment]
You're the best!
Thank you so much. Gonna test it tomorrow and get back to you.

**Comment by jmdvella** [comment]
No worries, let me know if you run into any further issues. 👍


Cheers,
James Vella
www.jamesvella.net

**Comment by MatMachina** [comment]
Worked like bloody charm! 👍
You're a wizard James. Thank you so much. 
With this script you've made my life so much easier, my boss very happy and made it possible for me to continue to work
...sh*t! ^^

**Comment by jmdvella** [comment]
Great to hear it Mat! Thanks for the kind words.

I'm hoping to update it in the future to support more textures so if you
come across anything you think it needs let me know 👍

**Comment by MatMachina** [comment]
Awesome stuff.

One thing does come to mind, now that I'm test rendering in Blender: transparency (ie glass materials) doesn't seem to transfer to the Principled BSDF. I'm guessing that's cos of the way it's handled by the 2 material types and it's really no biggie to change it manually, but if you did happen to create a solution it'd be sweet.

Thanks again for your work and have a great one mate.

**Comment by jmdvella** [comment]
Can you show me a screenshot? Both in 3dsmax and then in blender? Mine come
in as Principled BRDF when setup in 3dsmax/vray as PBR/Opacity. Is this
using Refraction, Translucency etc? Show me the material setup


Cheers,
James Vella
www.jamesvella.net

**Comment by MatMachina** [comment]
Of course.
And mine comes in as a Principled BSDF too, just that the transmission does nothing when changed.

This is the VRayMtl before I use your converter:
![image](https://user-images.githubusercontent.com/110823697/183612483-362826c3-b3a7-4b04-8897-b9e98b290e87.png)

This is the material after:
![image](https://user-images.githubusercontent.com/110823697/183612922-bc6eab39-8a06-46c3-9142-b730916803b2.png)
The maps that aren't plugged in, I wasn't planning on using... and now I feel totally stupid, cos i realise that the opacity has no value set due to there being a map for it while it was a VRayMtl and I completely missed that.

However! When I render in Blender, even after changing the transmission, there is no transparency visible in Cycles.
Here is the Blender setup:
![image](https://user-images.githubusercontent.com/110823697/183614598-a7630aa3-3415-4079-a1bb-ec6c01977de4.png)

**Comment by jmdvella** [comment]
Great thanks. Which texture do you need in transmission?

Not sure if it's possible using the standard legacy material in 3dsmax but
ill see if there is a way.

**Comment by MatMachina** [comment]
That's what I though. Like I said, it's no problem changing it manually, it's only a few clicks.

No texture, just translucency and dirt controlled through either roughness or glossiness.

Thank you again for taking the time and being such a mad lad!

**Comment by jmdvella** [comment]
Just so i understand, you want the roughness texture plugged into the
transmission?

**Comment by MatMachina** [comment]
Sorry, nah. Transmission is without texture, but the roughness map in the roughness or the glossiness in the specular of the BSDF.

**Comment by jmdvella** [comment]
Specular should be 0.5 and roughness goes into the roughness slot. Not
really sure how you want to adjust transmission, if its a value then it
will be done in blender. This script is for converting pbr roughness vray
materials. Ior not required either in roughness workflow as it uses
metallic (on/off)

**Comment by MatMachina** [comment]
Got ya. I was thinking that something like that would be the answer.
Haven't used blender in quite a few years.

Thanks a lot for the knowledge and time. I really do appreciate it. You've been a huge help!

**Comment by jmdvella** [comment]
Glad to help.

I don't use blender much myself, but i sell 3D models so i wanted to make
sure it was in parity with all apps. I have some scripts fot C4D but i
haven't posted them online at this stage.

Thanks for the feedback!
