### ISSUE TITLE
Issue as attached - error in code line 64 - 3dsmax 2022

### ISSUE THREAD

**Issue by BlueWaves3005** [jmdvella/3dsmax-scripts#4]
![3dsmax-vray-converter](https://user-images.githubusercontent.com/92517105/197273987-472369bc-a0ab-4192-8568-9a65a83300b1.jpg)

**Comment by jmdvella** [comment]
Try VrayToFBX_v01.01.ms instead. This looks like an old version.


Cheers,
James Vella
www.jamesvella.net
